baseURL = "http://isoft.cnu.ac.kr/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name="mydeploy"
URL="http://isoft.cnu.ac.kr/"

