baseURL = "http://isoft.cnu.ac.kr/"
languageCode = "en-us"
title = "Intelligent Software laboratory"
enableRobotsTXT=true
theme = "ananke"


[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name="mydeploy"
URL="http://isoft.cnu.ac.kr/"

